services:
  - type: web
    name: healthy-server
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: API_URL
        value: https://healthy-server.onrender.com
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: DATABASE_URL
        fromDatabase:
          name: healthy-db
          property: connectionString

databases:
  - name: healthy-db
    databaseName: healthy_db
    user: healthy_user
    plan: free 